/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualizacao;

/**
 *
 * @author dsm-2
 */
public class frmHomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form frmAdmin
     */
    public frmHomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelLilas = new javax.swing.JPanel();
        jPanelBranco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        linkCurso = new javax.swing.JMenuItem();
        linkModulo = new javax.swing.JMenuItem();
        linkProfessor = new javax.swing.JMenuItem();
        linkAdm = new javax.swing.JMenuItem();
        linkAluno = new javax.swing.JMenuItem();
        barVoltar = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jpanelLilas.setBackground(new java.awt.Color(204, 102, 255));

        jPanelBranco.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualizacao/icones/MicrosoftTeams-image.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBrancoLayout = new javax.swing.GroupLayout(jPanelBranco);
        jPanelBranco.setLayout(jPanelBrancoLayout);
        jPanelBrancoLayout.setHorizontalGroup(
            jPanelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBrancoLayout.setVerticalGroup(
            jPanelBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpanelLilasLayout = new javax.swing.GroupLayout(jpanelLilas);
        jpanelLilas.setLayout(jpanelLilasLayout);
        jpanelLilasLayout.setHorizontalGroup(
            jpanelLilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLilasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBranco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelLilasLayout.setVerticalGroup(
            jpanelLilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLilasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBranco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setForeground(new java.awt.Color(102, 102, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualizacao/icones/configuracao.png"))); // NOI18N
        jMenu1.setText("Gerenciamento");

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setForeground(new java.awt.Color(102, 102, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualizacao/icones/adicionar-ficheiro.png"))); // NOI18N
        jMenu2.setText("Cadastros");

        linkCurso.setBackground(new java.awt.Color(255, 255, 255));
        linkCurso.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        linkCurso.setForeground(new java.awt.Color(102, 102, 255));
        linkCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualizacao/icones/icon-curso.png"))); // NOI18N
        linkCurso.setText("Curso");
        linkCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkCursoActionPerformed(evt);
            }
        });
        jMenu2.add(linkCurso);

        linkModulo.setBackground(new java.awt.Color(255, 255, 255));
        linkModulo.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        linkModulo.setForeground(new java.awt.Color(102, 102, 255));
        linkModulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualizacao/icones/modulo.png"))); // NOI18N
        linkModulo.setText("Módulo");
        linkModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkModuloActionPerformed(evt);
            }
        });
        jMenu2.add(linkModulo);

        linkProfessor.setBackground(new java.awt.Color(255, 255, 255));
        linkProfessor.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        linkProfessor.setForeground(new java.awt.Color(102, 102, 255));
        linkProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualizacao/icones/professora.png"))); // NOI18N
        linkProfessor.setText("Professor");
        linkProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkProfessorActionPerformed(evt);
            }
        });
        jMenu2.add(linkProfessor);

        linkAdm.setBackground(new java.awt.Color(255, 255, 255));
        linkAdm.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        linkAdm.setForeground(new java.awt.Color(102, 102, 255));
        linkAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualizacao/icones/perfilAdm.png"))); // NOI18N
        linkAdm.setText("Administrador");
        linkAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkAdmActionPerformed(evt);
            }
        });
        jMenu2.add(linkAdm);

        linkAluno.setBackground(new java.awt.Color(255, 255, 255));
        linkAluno.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        linkAluno.setForeground(new java.awt.Color(102, 102, 255));
        linkAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualizacao/icones/aprendizagem-online.png"))); // NOI18N
        linkAluno.setText("Aluna");
        linkAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(linkAluno);

        jMenu1.add(jMenu2);

        barVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        barVoltar.setForeground(new java.awt.Color(102, 102, 255));
        barVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualizacao/icones/seta-esquerda.png"))); // NOI18N
        barVoltar.setText("Voltar");
        barVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barVoltarMouseClicked(evt);
            }
        });
        jMenu1.add(barVoltar);

        jMenuSair.setBackground(new java.awt.Color(255, 255, 255));
        jMenuSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuSair.setForeground(new java.awt.Color(102, 102, 255));
        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visualizacao/icones/sair.png"))); // NOI18N
        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenu1.add(jMenuSair);

        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(102, 102, 255));
        jMenu3.setText("Liberty Cursos");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setMargin(new java.awt.Insets(0, 250, 0, 0));
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelLilas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelLilas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void linkCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkCursoActionPerformed
        // TODO add your handling code here:
        frmCadCurso formcur = new frmCadCurso();
        formcur.setVisible(true);
        
    }//GEN-LAST:event_linkCursoActionPerformed

    private void linkAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkAlunoActionPerformed
        // TODO add your handling code here:
        frmCadAluna formcadalu = new frmCadAluna();
        formcadalu.setVisible(true);
    }//GEN-LAST:event_linkAlunoActionPerformed

    private void linkModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkModuloActionPerformed
        // TODO add your handling code here:
        frmCadModulo formmod = new frmCadModulo();
        formmod.setVisible(true);
    }//GEN-LAST:event_linkModuloActionPerformed

    private void linkProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkProfessorActionPerformed
        // TODO add your handling code here:
        frmCadProfessor formprof = new frmCadProfessor();
        formprof.setVisible(true);
    }//GEN-LAST:event_linkProfessorActionPerformed

    private void linkAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkAdmActionPerformed
        // TODO add your handling code here:
        frmCadAdm formcadadm = new frmCadAdm();
        formcadadm.setVisible(true);
    }//GEN-LAST:event_linkAdmActionPerformed

    private void barVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barVoltarMouseClicked
        // TODO add your handling code here:
        frmPrincipal formlog = new frmPrincipal();
        formlog.setVisible(true);
        
    }//GEN-LAST:event_barVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu barVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelBranco;
    private javax.swing.JPanel jpanelLilas;
    private javax.swing.JMenuItem linkAdm;
    private javax.swing.JMenuItem linkAluno;
    private javax.swing.JMenuItem linkCurso;
    private javax.swing.JMenuItem linkModulo;
    private javax.swing.JMenuItem linkProfessor;
    // End of variables declaration//GEN-END:variables
}
